"""
Tests for cases API: amount handling, scenario ID lookup, claim verdicts, and human review.
"""
import time
from fastapi.testclient import TestClient

from app.main import app
from app.db.session import SessionLocal
from app.db.models import Case, Evidence, Claim

client = TestClient(app)


def test_seeded_strong_transaction_overrides_incorrect_amount():
    resp = client.post("/cases/", json={
        "transaction_id": "DEMO_SCN_01_TESTSUFFIX",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "test claim",
        "amount": 0,
    })
    assert resp.status_code == 201
    data = resp.json()
    assert data["amount"] == 299.99, f"Expected 299.99, got {data['amount']}"


def test_seeded_weak_transaction_overrides_incorrect_amount():
    resp = client.post("/cases/", json={
        "transaction_id": "DEMO_SCN_05",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "test claim",
        "amount": 500,
    })
    assert resp.status_code == 201
    data = resp.json()
    assert data["amount"] == 120.00


def test_case_currency_matches_verified_payment_evidence():
    resp = client.post("/cases/", json={
        "transaction_id": "DEMO_SCN_11_CURRENCY_CHECK",
        "merchant_id": "M1",
        "dispute_reason": "duplicate charge",
        "customer_claim": "test claim",
        "amount": 0,
    })
    assert resp.status_code == 201
    case_id = resp.json()["id"]

    detail = client.get(f"/cases/{case_id}").json()
    payment = next(e for e in detail["evidence"] if e["evidence_type"] == "payment")
    assert detail["currency"] == payment["content"]["currency"] == "USD"
    assert detail["amount"] == payment["content"]["amount"] == 199.99


def test_random_transaction_uses_submitted_amount():
    resp = client.post("/cases/", json={
        "transaction_id": "RANDOM_TXN_123",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "test claim",
        "amount": 499.99,
    })
    assert resp.status_code == 201
    data = resp.json()
    assert data["amount"] == 499.99


def test_demo_info_endpoint():
    r1 = client.get("/cases/demo-info/DEMO_SCN_01_ABCD")
    assert r1.status_code == 200
    assert r1.json() == {"is_demo": True, "expected_amount": 299.99}

    r3 = client.get("/cases/demo-info/DEMO_TXN_INVALID_123")
    assert r3.status_code == 200
    assert r3.json() == {"is_demo": False}

    r4 = client.get("/cases/demo-info/RANDOM_TXN_123")
    assert r4.status_code == 200
    assert r4.json() == {"is_demo": False}


def test_scenario_base_id_lookup_and_claim_verdicts():
    """
    Create a case with a suffixed scenario ID (DEMO_SCN_02_UNIQUERANDOM).
    The TestClient runs BackgroundTasks synchronously, so the pipeline
    should complete before we read the case back.
    Evidence must be retrieved using the base DEMO_SCN_02 seed.
    All claims must have non-null verdicts after the mock investigation.
    """
    resp = client.post("/cases/", json={
        "transaction_id": "DEMO_SCN_02_UNIQUERANDOM",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "never delivered",
        "amount": 89.99,
    })
    assert resp.status_code == 201
    case_id = resp.json()["id"]

    # BackgroundTasks run synchronously in TestClient — pipeline is already done
    r_case = client.get(f"/cases/{case_id}")
    assert r_case.status_code == 200
    data = r_case.json()

    # Evidence should be populated from DEMO_SCN_02 base seed
    evidence = data["evidence"]
    assert len(evidence) > 0, "Evidence should be retrieved using base scenario ID strip"

    # Claims must have been generated
    claims = data["claims"]
    assert len(claims) > 0, "Claims should have been generated by the orchestrator"

    # Every claim must have a verdict (not None) after deterministic post-investigation step
    for claim in claims:
        assert claim["verdict"] in ("supported", "contradicted", "unverifiable"), (
            f"Claim verdict must be set, got: {claim['verdict']!r}"
        )
        assert claim["confidence"] is not None, "Claim confidence must be set"


def test_demo_cases_produce_unique_ids():
    """
    Two cases created from the same scenario template must have different IDs.
    """
    resp1 = client.post("/cases/", json={
        "transaction_id": "DEMO_SCN_03_SUFFIX_A",
        "merchant_id": "M1",
        "dispute_reason": "duplicate charge",
        "customer_claim": "charged twice",
        "amount": 599.99,
    })
    resp2 = client.post("/cases/", json={
        "transaction_id": "DEMO_SCN_03_SUFFIX_B",
        "merchant_id": "M1",
        "dispute_reason": "duplicate charge",
        "customer_claim": "charged twice",
        "amount": 599.99,
    })
    assert resp1.status_code == 201
    assert resp2.status_code == 201
    assert resp1.json()["id"] != resp2.json()["id"], "Two cases must have different IDs"
    assert resp1.json()["transaction_id"] != resp2.json()["transaction_id"]


def test_human_review_approve():
    resp = client.post("/cases/", json={
        "transaction_id": "RANDOM_REVIEW_A",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "test claim",
        "amount": 100.00,
    })
    case_id = resp.json()["id"]

    r = client.post(f"/cases/{case_id}/review", json={"action": "approve", "notes": "LGTM"})
    assert r.status_code == 200
    assert r.json()["ai_recommendation"] == "ESCALATE"
    assert r.json()["status"] == "escalated"
    assert r.json()["final_action"] == "ESCALATE"

def test_human_review_escalate():
    resp = client.post("/cases/", json={
        "transaction_id": "RANDOM_REVIEW_B",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "test claim",
        "amount": 100.00,
    })
    case_id = resp.json()["id"]

    r = client.post(f"/cases/{case_id}/review", json={"action": "escalate", "notes": "Manager needed"})
    assert r.status_code == 200
    assert r.json()["ai_recommendation"] == "ESCALATE"
    assert r.json()["status"] == "escalated"
    assert r.json()["final_action"] == "escalate"

def test_human_review_request_more_evidence():
    resp = client.post("/cases/", json={
        "transaction_id": "RANDOM_REVIEW_C",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "test claim",
        "amount": 100.00,
    })
    case_id = resp.json()["id"]

    r = client.post(f"/cases/{case_id}/review", json={"action": "request_more_evidence", "notes": "Need tracking"})
    assert r.status_code == 200
    assert r.json()["ai_recommendation"] == "ESCALATE"
    assert r.json()["status"] == "escalated"
    assert r.json()["final_action"] == "request_more_evidence"

def test_human_review_invalid_action():
    resp = client.post("/cases/", json={
        "transaction_id": "RANDOM_REVIEW_D",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "test claim",
        "amount": 100.00,
    })
    case_id = resp.json()["id"]

    # Backend validates action manually and raises HTTPException(400)
    r = client.post(f"/cases/{case_id}/review", json={"action": "invalid_action", "notes": ""})
    assert r.status_code == 400


def test_human_review_audit_trail():
    resp = client.post("/cases/", json={
        "transaction_id": "RANDOM_REVIEW_AUDIT",
        "merchant_id": "M1",
        "dispute_reason": "product not received",
        "customer_claim": "test claim",
        "amount": 100.00,
    })
    case_id = resp.json()["id"]

    client.post(f"/cases/{case_id}/review", json={"action": "approve", "notes": "Approved"})

    r_audit = client.get(f"/cases/{case_id}/audit")
    assert r_audit.status_code == 200
    logs = r_audit.json()
    review_logs = [log for log in logs if log["step"] == "human_review_decision"]
    assert len(review_logs) == 1
    assert review_logs[0]["detail"]["action"] == "approve"
    assert review_logs[0]["detail"]["notes"] == "Approved"

def test_demo_reset_disabled_in_production():
    from app.config import settings
    
    # Save original
    original_env = settings.environment
    original_demo = settings.demo_mode
    
    try:
        # Simulate production environment
        settings.environment = "production"
        settings.demo_mode = False
        
        r = client.delete("/cases/demo-reset")
        assert r.status_code == 403
        assert "disabled" in r.json()["detail"]
        
        # Simulate development environment
        settings.environment = "development"
        r2 = client.delete("/cases/demo-reset")
        assert r2.status_code == 200
        
        # Simulate production but demo_mode = True
        settings.environment = "production"
        settings.demo_mode = True
        r3 = client.delete("/cases/demo-reset")
        assert r3.status_code == 200
        
    finally:
        settings.environment = original_env
        settings.demo_mode = original_demo
